---
- name: Deploy Portfolio WebApp to All VMs
  hosts: all
  become: yes

  tasks:

    # ------------------------------
    # 1) INSTALL DOCKER
    # ------------------------------

    - name: Install Docker on Ubuntu
      when: ansible_os_family == "Debian"
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker on CentOS
      when: ansible_os_family == "RedHat"
      shell: |
        curl -fsSL https://get.docker.com/ | sh

    - name: Enable & Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    # ------------------------------
    # 2) COPY TAR TO REMOTE SERVER
    # ------------------------------

    - name: Copy docker tarball to server
      copy:
        src: portfolio-webapp.tar
        dest: /tmp/portfolio-webapp.tar
        mode: '0644'

    # ------------------------------
    # 3) LOAD DOCKER IMAGE
    # ------------------------------

    - name: Load docker image from tarball
      shell: docker load -i /tmp/portfolio-webapp.tar
      register: load_output

    - debug:
        msg: "{{ load_output.stdout }}"

    # ------------------------------
    # 4) REMOVE OLD CONTAINER
    # ------------------------------

    - name: Remove old container if exists
      shell: docker rm -f portfolio-webapp || true

    # ------------------------------
    # 5) RUN NEW CONTAINER
    # ------------------------------

    - name: Run the portfolio webapp container
      shell: docker run -d --name portfolio-webapp -p 80:80 portfolio-webapp:latest
