---
- name: Build docker image for web app
  hosts: local
  connection: local
  become: yes
  become_method: sudo

  tasks:

    - name: Remove conflicting containerd packages
      apt:
        name:
          - containerd
          - containerd.io
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Install Docker using official Docker convenience script
      shell: curl -fsSL https://get.docker.com | sh

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Build docker image
      community.docker.docker_image:
        name: portfolio-webapp
        tag: latest
        build:
          path: .
          dockerfile: Dockerfile
        source: build
        force_source: yes

    - name: Save docker image to tarball
      command: docker save portfolio-webapp:latest -o portfolio-webapp.tar
      args:
        chdir: "{{ playbook_dir }}"
